spring:
  datasource:
    url: jdbc:h2:mem:country?createDatabaseIfNotExist=true
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

server:
  port: 8080

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
